kumuluzee:
  name: shippings
  env:
    name: dev
  version: 1.0.0
  server:
    base-url: http://localhost:8086
    http:
      port: 8086
  datasources:
    - jndi-name: jdbc/ShippingsDS
      connection-url: jdbc:postgresql://192.168.99.100:5432/shipping
      username: dbuser
      password: postgres
      max-pool-size: 20
  discovery:
    etcd:
      hosts: http://192.168.99.100:2379
  cors-filter:
    servlet:
      allow-origin: "*"
  metrics:
      web-instrumentation:
        - name: shippings-endpoint
          url-pattern: /v1/shippings/*
rest-properties:
  external-services:
    order-service:
      enabled: true
