apiVersion: v1
kind: Service
metadata:
  name: shipping
  labels:
    app: shipping
spec:
  type: NodePort
  ports:
  - name: server
    port: 8089
    protocol: TCP
    targetPort: 8089
  selector:
    app: shipping