apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: shipping-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shipping
    spec:
      containers:
      - image: bozen/shippings:0.01
        name: shippings
        env:
          - name: KUMULUZEE_DISCOVERY_CLUSTER
            value: bluemix
          - name: KUMULUZEE_DISCOVERY_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_CONFIG_ETCD_HOSTS
            value: http://etcd:2379
          - name: KUMULUZEE_DATASOURCES0_CONNECTIONURL
            value: jdbc:postgresql://postgres-shippings:5432/shipping
          - name: KUMULUZEE_SERVER_BASEURL
            value: http://169.51.20.134:30597
        ports:
        - containerPort: 8086
          name: server
          protocol: TCP